added custom sheep
Pjiwm/kaizominecraft pull request #3
Opened 2021-06-07 19:28 UTC by Pjiwm

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

**Please provide enough information so that others can review your pull request:**
Added custom mob behavior for the following mobs:

- [x] sheep  
- [ ] cow
- [ ] iron golem
- [ ] pig
- [ ] pig zombie
- [ ] wolf

**Explain the **details** for making this change. What existing problem does the pull request solve?**
Changed behavior for mobs to increase game difficulty.
Sheeps now run faster and are always on the run for players.

**Test plan (required):**
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request has visual changes.
Summon sheep.

**Closing issues**
#1 

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2021-06-08 17:00 UTC, Pjiwm commented
Implemented custom mobs:
- sheep
-  cow
-  iron golem
-  pig
-  pig zombie
-  wolf
All mobs are implemented correctly and have the appropriate behavior
closes #1

2021-06-09 13:41 UTC, KaanMol requested changes
A lot of empty spaces, can you remove them?

2021-06-09 13:41 UTC, KaanMol commented on src/main/java/nl/pjiwm/kaizominecraft/mobs/CustomWolf.java
> +
Maybe remove the extra spaces?

2021-06-09 13:41 UTC, KaanMol commented on src/main/java/nl/pjiwm/kaizominecraft/mobs/CustomPigZombie.java
> +
Also spaces here

2021-06-09 13:41 UTC, KaanMol commented on src/main/java/nl/pjiwm/kaizominecraft/mobs/CustomIronGolem.java
> +
More empty spaces

2021-06-09 13:46 UTC, KaanMol approved these changes

2021-06-09 13:46 UTC, merged